### PR TITLE
Fix EditCompanyName bug

### LINKED ISSUE #46: CompanyName cannot edited by EDIT command
When using `edit 1 cn/xxxx` as input, program shows `At least one field to edit must be provided.`

### PR DESCRIPTION
**Pull request by Lalelulilulela**
fix #46 
Ensure that company name can be edited

### CODE REVIEW

**Comment by ashleyy2444** [comment]
LGTM

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -200,7 +200,7 @@ public EditPersonDescriptor(EditPersonDescriptor toCopy) {
          * Returns true if at least one field is edited.
          */
         public boolean isAnyFieldEdited() {
-            return CollectionUtil.isAnyNonNull(name, phone, email, address, dateTime, salary, info, tags,
+            return CollectionUtil.isAnyNonNull(companyName, name, phone, email, address, dateTime, salary, info, tags,
```
Comment (ashleyy2444) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:203]: Good job fixing the error

**Comment by ashleyy2444** [comment]
LGTM
