### PR TITLE
Fix error and success messages

### LINKED ISSUE #108: [PE-D][Tester C] Missing spaces in invalid filter command message
Please refer to the image, missing spaces between filter and tags.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: caitlyntang/ped#2

### LINKED ISSUE #117: [PE-D][Tester B] Lack of spacing in output message
When adding a new person, there is no space between the salary and the info, making it harder to read.

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: bryanyee33/ped#6

### LINKED ISSUE #127: [PE-D][Tester D] Invalid command format issue with filter
```
filter filtert/Tag
````

Output: 

Expected output : I not so sure about expected output, but i believe there is some inconsistency or typo in error messages at Parameter : 

It shows filtert/Tag
instead of showing t/Tag (which i believe this is your intention)

It might cause confusion to user since the parameter shown to user is inconsistent to the example shown

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: chiageng/ped#9

### LINKED ISSUE #165: Company name added not shown in success message upon adding a person
image

### PR DESCRIPTION
**Pull request by Lalelulilulela**
- fix error message of FilterCommand.java
- fix success message of AddCommand.java
- fix error message of FilterInterviewTimeCommand.java

resolves #165 
resolves #127
resolves #117
resolves #108

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/FilterInterviewTimeCommand.java [hunk 1]
```diff
@@ -26,10 +26,12 @@ public class FilterInterviewTimeCommand extends FilterCommand {
...
             + "- " + COMMAND_WORD + "before/020220241100 after/020220251100 from/030420240800-020520241100";
     public static final String WRONG_INTERVIEW_TIME_RANGE_MESSAGE = "INTERVIEW_TIME_RANGE should be in the form of:\n"
-            + "before/INTERVIEW_TIME\nor\n"
-            + "after/INTERVIEW_TIME\nor\n"
-            + "from/INTERVIEW_TIME-INTERVIEW_TIME\n"
-            + "where INTERVIEW_TIME is in the form: " + InterviewTime.INTERVIEW_TIME_FORMAT
+            + "- before/INTERVIEW_TIME\n"
+            + "- after/INTERVIEW_TIME\n"
+            + "- from/INTERVIEW_TIME-INTERVIEW_TIME\n"
+            + "where there are no white spaces before and after the '-' "
```
Comment (dabzpengu) [inline src/main/java/seedu/address/logic/commands/FilterInterviewTimeCommand.java]: a suggestion would be `before and after the hyphen` or `before and after '-'`, same goes for other references to '-'

**Review by dabzpengu — COMMENTED** [review]
LGTM, left a suggestion, but up to you

File: src/main/java/seedu/address/logic/commands/FilterInterviewTimeCommand.java (hunk 1 above)
Comment (Lalelulilulela) [reply src/main/java/seedu/address/logic/commands/FilterInterviewTimeCommand.java]: ok I will use `before and after '-'`
