### PR TITLE
Resolve bug for delete tag command

### LINKED ISSUE #91: Resolve Bug For Delete Tag Feature

### LINKED ISSUE #125: [PE-D][Tester C] Delete using tag function does not seem to be working
First I ran the command `find jane`

Then ran `delete t/owesMoney`

However, the person tagged with `owesMoney` is not deleted.

Please also refer to the video for more information.
<i><video controls><source src="https://raw.githubusercontent.com/caitlyntang/ped/main/files/80a00125-df85-4170-b8d1-68c3fd6281d3.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/caitlyntang/ped/main/files/80a00125-df85-4170-b8d1-68c3fd6281d3.mp4</i>.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: caitlyntang/ped#4

### LINKED ISSUE #130: [PE-D][Tester D] delete using t/ bugs
```
delete t/colleagues
```

Output : 

Expected output : Delete all contact with tag colleagues (as shown in UG)

Apparently this command doesnt work on my side, i have tried a few times, even trying to do list again after delete command, but it seem doesnt work

You might want to check delete command again.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: chiageng/ped#10

### LINKED ISSUE #150: [PE-D][Tester B] Delete by tag does not work
After executing the command `delete t/family`, all contacts with the `family` tag still remain, and no one seems to be deleted.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: bryanyee33/ped#14

### PR DESCRIPTION
**Pull request by ashleyy2444**
closes #150
closes #130 
closes #125
closes #91

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/DeleteTagCommand.java [hunk 1]
```diff
@@ -42,10 +44,15 @@ public DeleteTagCommand(TagContainsKeywordsPredicate tagToDelete) {
     @Override
     public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
-        model.getFilteredPersonList().stream()
-                .filter(person -> person.getTags().contains(tagToDelete))
-                .forEach(person -> model.deletePerson(person));
-
+        List<Tag> tags = tagToDelete.getTags();
+        System.out.println("Deleting all contacts with tag: " + tags);
```
Comment (Lalelulilulela) [inline src/main/java/seedu/address/logic/commands/DeleteTagCommand.java:48]: Is this a debugging line?

**Review by Lalelulilulela — COMMENTED** [review]
LGTM

File: src/main/java/seedu/address/logic/commands/DeleteTagCommand.java (hunk 1 above)
Comment (ashleyy2444) [reply src/main/java/seedu/address/logic/commands/DeleteTagCommand.java:48]: Nope :D
