### PR TITLE
fix interviewtime not optional

### LINKED ISSUE #109: [PE-D][Tester D] Add command email field error
```
add cn/COMPANY_NAME n/NAME p/888888 e/johndoe@example.com a/ADDRESS
add cn/Google n/John Doe p/98765432 e/johnd@example.com a/test
```

Output : 

Expected output : I expect this code to be able to execute. I have tried even with your example code to double check, apparently, the error is that, this code is not throwing any error message, it is just stuck in the second example command. It doesnt help even though i shift a/ to infront of the code

I believe if you wish to have a specific address, you might want to throw a more detail exception messages. Or if not, this command should work

You might want to check regex in Address and error catching for add command

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: chiageng/ped#4

### LINKED ISSUE #139: [PE-D][Tester D] UG Command Summary Add & Add bug
```
add cn/Google n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25
```

The command listed in command summary is not working.

This command is just dont execute or dont throw any error messages which i dont understand why. I have checked that i have inserted all the compulsory fields but it does not working

I am not able to provide fix bug direction here as i am not sure whats going on here

[short note : I somehow able to execute the code as long as i define tt/, there might be a mistake either in your code for compulsory prefix and you miss out tt/ as compulsory prefix in ug]

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: chiageng/ped#14

### LINKED ISSUE #154: [PE-D][Tester B] Interview time is mandatory
The UG denotes that the interview time is optional in the add command. However, when you exclude this field, no contact is added and the result screen still remains in its previous state, with no warnings or indication of what has happened. (does not fail gracefully)

Example: `add cn/Google n/John Doe p/98765432 e/johnd@example.com a/311, Clement`

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: bryanyee33/ped#17

### LINKED ISSUE #158: [PE-D][Tester A] Filter Command: With tt/
Tried to use the filter command: filter tt/after/000000000000 but it output: Error thrown, date and time format may be wrong. Check UG.

I don't see anywhere within the UG that doesn't allow me to do that. Perhaps a better error message can be thrown?

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: YuSoonZ/ped#13

### PR DESCRIPTION
**Pull request by dabzpengu**
fix issue with interviewtime not being optional

if interviewtime is not given, command can still be executed and on the addressbook, interviewtime is reflected as "No interviews set"
example input: `add cn/Google n/Test p/98765432 e/johnd@example.com a/311`
image

closes #158 
closes #154 
closes #109 
closes #139

### CODE REVIEW

File: src/main/java/seedu/address/model/person/InterviewTime.java [hunk 1]
```diff
@@ -31,9 +31,12 @@ public class InterviewTime {
      * @param dateTime input
      */
     public InterviewTime(String dateTime) {
-        requireNonNull(dateTime);
-        checkArgument(isValidInterviewTime(dateTime), MESSAGE_CONSTRAINTS);
-        this.dateTime = LocalDateTime.parse(dateTime, formatter); //set format
+        if (dateTime == null) {
+            this.dateTime = null;
+        } else {
```
Comment (Lalelulilulela) [inline src/main/java/seedu/address/model/person/InterviewTime.java:36]: Nice handling of null interview times

**Review by Lalelulilulela — COMMENTED** [review]
LGTM

**Comment by ZHANGTIANYAO1** [comment]
LGTM
